name: Update Spotify Playlist Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs the script every day at midnight UTC
  workflow_dispatch:  # Allows for manual triggering

jobs:
  update_playlist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Spotify automation script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: 'http://localhost:8080'
        run: python spotify_automation.py
